apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: example-app

labels:
- pairs:
    environment: staging
  includeSelectors: true

namePrefix: staging-

replicas:
- name: example-app
  count: 2

patches:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: example-app
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: 128Mi
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/cpu
      value: 200m
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: 256Mi
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/cpu
      value: 500m

configMapGenerator:
- name: example-config
  behavior: merge
  literals:
  - flask_env=staging
  - log_level=INFO

images:
- name: ashik9001/demo-app
  newTag: staging-latest
