apiVersion: v1
kind: Service
metadata:
  name: {APP_NAME}
  labels:
    app: {APP_NAME}
spec:
  type: ClusterIP
  selector:
    app: {APP_NAME}
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http
