apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: example-app

labels:
- pairs:
    environment: dev
  includeSelectors: true

namePrefix: dev-

replicas:
- name: example-app
  count: 1

patches:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: example-app
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: 64Mi
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/cpu
      value: 100m
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: 128Mi
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/cpu
      value: 250m

configMapGenerator:
- name: example-config
  behavior: merge
  literals:
  - flask_env=development
  - log_level=DEBUG

images:
- name: ashik9001/demo-app
  newTag: dev-latest
