apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: example-app

labels:
- pairs:
    app: example-app
  includeSelectors: true

resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- configmap.yaml

# Images will be patched by CI/CD and overlays
images:
- name: ashik9001/demo-app
  newName: ashik9001/demo-app
  newTag: latest

# These are placeholder replicas - overridden by overlays
replicas:
- name: example-app
  count: 3


