apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

namespace: {NAMESPACE}

commonLabels:
  environment: staging

namePrefix: staging-

replicas:
- name: {APP_NAME}
  count: 2

patchesStrategicMerge:
- deployment-patch.yaml

configMapGenerator:
- name: {APP_NAME}-config
  behavior: merge
  literals:
  - flask_env=staging
  - log_level=INFO

images:
- name: {REGISTRY_IMAGE}
  newTag: staging-latest
